version: '3.1'
services:
  webkoperasi:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8075:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=myodoo
    networks:
      - koperasinet
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    networks:
      - koperasinet
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - koperasinet

networks:
  koperasinet:
